name: "SCR_lt_speech_commands"
taskrc:
  merge: True
datarc:
  # root_path: containing wav files
  # data_path: containing csv files
  root_path: /storage/SpeechPrompt/datasets/SpeechPrompt-SCR/lt_speech_commands
  data_path: /storage/SpeechPrompt/datasets/SpeechPrompt-SCR/lt_speech_commands
  batch_size: 16
  num_workers: 8
