name: "SCR_ar_speech_commands"
taskrc:
  merge: True
datarc:
  root_path: /storage/SpeechPrompt/datasets/SpeechPrompt-SCR/ar_speech_commands
  data_path: /storage/SpeechPrompt/datasets/SpeechPrompt-SCR/ar_speech_commands
  batch_size: 16
  num_workers: 8
